# Airport info
In this notebook we first define some airport deatails and send them to SQL afterwards

In [6]:
import pandas as pd
import config

In [7]:
data=[[1,"BER","Berlin Brandenburg Airport"],[2,"ARN","Stockholm Arlanda Airport"],[2,"BMA","Stockholm Bromma Airport"]]
airports = pd.DataFrame(data, columns=['city_id', 'iata_code',"airport_name"])

In [8]:
airports

   city_id iata_code                airport_name
0        1       BER  Berlin Brandenburg Airport
1        2       ARN   Stockholm Arlanda Airport
2        2       BMA    Stockholm Bromma Airport

In [9]:
import sqlalchemy #connecting to your sql
import pymysql
host = config.host
schema = config.schema
user = config.user
password = config.password
port = config.port
con = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'
        
        
airports.to_sql('airports',con=con,if_exists='append',index=False)#filling the empty table in sql

IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'BER' for key 'airports.PRIMARY'")
[SQL: INSERT INTO airports (city_id, iata_code, airport_name) VALUES (%(city_id)s, %(iata_code)s, %(airport_name)s)]
[parameters: ({'city_id': 1, 'iata_code': 'BER', 'airport_name': 'Berlin Brandenburg Airport'}, {'city_id': 2, 'iata_code': 'ARN', 'airport_name': 'Stockholm Arlanda Airport'}, {'city_id': 2, 'iata_code': 'BMA', 'airport_name': 'Stockholm Bromma Airport'})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)